# Generated by Django 3.1.6 on 2021-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offers',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='offers',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
