# Generated by Django 3.1.7 on 2021-03-14 09:12

from django.db import migrations


def add_location(apps, schema_editor):
    """
        Adds the Locaton to the model
    """
    offers = apps.get_model('offers', 'Offers')
    location = apps.get_model('offers', 'Location')

    for offer in offers.objects.all():
        try:
            loc = location(name=offer.location)
            loc.save()
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_location'),
    ]

    operations = [
        migrations.RunPython(add_location),
    ]
