# Generated by Django 3.1.7 on 2021-03-14 09:23

from django.db import migrations, models
import django.db.models.deletion


def add_location_to_offer(apps, schema_editor):
    """
        Adds the Locaton to the model
    """
    offers = apps.get_model('offers', 'Offers')
    location = apps.get_model('offers', 'Location')

    for offer in offers.objects.all():
        loc = location.objects.get(name=offer.location)
        offer.locations = loc
        offer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20210314_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.location', verbose_name='offer_location'),
        ),
        migrations.AddField(
            model_name='offers',
            name='top_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(add_location_to_offer),
    ]
