# Generated by Django 3.1.7 on 2021-03-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20210314_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='location',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='locations',
            new_name='location',
        ),
    ]
